# Generated by Django 5.2.4 on 2025-07-22 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(unique=True, verbose_name='Значение числа')),
                ('flag', models.BooleanField(default=False, verbose_name='Использовано')),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SettingNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.number')),
                ('setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.setting')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('setting', 'number')},
            },
        ),
        migrations.AddField(
            model_name='setting',
            name='numbers',
            field=models.ManyToManyField(through='frontend.SettingNumber', to='frontend.number', verbose_name='Выбранные числа'),
        ),
    ]
